version: "3.8"

services:
  discord-bot:
    container_name: discord-bot
    build: .
    command: python main.py
    volumes:
      - .:/app
    working_dir: /app
    restart: on-failure
    env_file:
      - .env
    networks:
      service-network:

networks:
  service-network:
    driver: bridge